#!/usr/bin/env bash
# Render the prebuilt-binary formula for a tag and push it to balintb/homebrew-tap.
# Called by .github/workflows/release.yml after GoReleaser has built the archives.
#
#   scripts/bump-formula.sh <tag>              # render from dist/checksums.txt, push to the tap
#   DRY_RUN=1 scripts/bump-formula.sh <tag>    # print the rendered formula; no clone, commit or push
#
# env: TAP_TOKEN  PAT with contents:write on homebrew-tap (unless DRY_RUN=1)
#      CHECKSUMS  path to the release checksums.txt; default: dist/checksums.txt
set -euo pipefail

TAG="${1:?usage: bump-formula.sh <tag>}"
VERSION="${TAG#v}"
NAME="llamago"
BASE="https://github.com/balintb/${NAME}/releases/download/${TAG}"
CHECKSUMS="${CHECKSUMS:-dist/checksums.txt}"

sha() { # $1 = os_arch, e.g. darwin_arm64 -> sha256 of llamago_<version>_<os_arch>.tar.gz
  local archive="${NAME}_${VERSION}_$1.tar.gz" sum=""
  [ -f "$CHECKSUMS" ] && sum="$(awk -v n="$archive" '$2==n{print $1}' "$CHECKSUMS")"
  if [ -z "$sum" ]; then
    if [ "${DRY_RUN:-}" = "1" ]; then
      sum="0000000000000000000000000000000000000000000000000000000000000000"
    else
      echo "no checksum for ${archive} in ${CHECKSUMS}" >&2
      exit 1
    fi
  fi
  echo "$sum"
}

# Looked up before rendering: a failure inside the heredoc below would not stop the script.
SHA_DARWIN_ARM64="$(sha darwin_arm64)"
SHA_DARWIN_AMD64="$(sha darwin_amd64)"
SHA_LINUX_ARM64="$(sha linux_arm64)"
SHA_LINUX_AMD64="$(sha linux_amd64)"

render() {
  cat <<EOF
# Generated by scripts/bump-formula.sh on release. Prebuilt-binary formula:
# Homebrew downloads the release archive (no quarantine -> no notarization needed).
class Llamago < Formula
  desc "TUI for Ollama: chat, manage installed models, compare them side by side"
  homepage "https://github.com/balintb/${NAME}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/${NAME}_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end
    on_intel do
      url "${BASE}/${NAME}_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${SHA_DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/${NAME}_${VERSION}_linux_arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end
    on_intel do
      url "${BASE}/${NAME}_${VERSION}_linux_amd64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
    end
  end

  def install
    bin.install "${NAME}"
  end

  def caveats
    <<~EOS
      ${NAME} talks to a running Ollama server and does not start one. For a local one:
        brew install ollama
        ollama serve

      Or point it at another server with: ${NAME} -host http://host:11434
    EOS
  end

  test do
    assert_match "${NAME} v#{version}", shell_output("#{bin}/${NAME} -version")
  end
end
EOF
}

FORMULA="$(render)"

if [ "${DRY_RUN:-}" = "1" ]; then
  echo "==> DRY RUN: rendering formula for ${TAG} (no push)" >&2
  echo "$FORMULA"
  exit 0
fi

: "${TAP_TOKEN:?TAP_TOKEN required (or set DRY_RUN=1)}"
TMP="$(mktemp -d)"
git clone "https://x-access-token:${TAP_TOKEN}@github.com/balintb/homebrew-tap.git" "$TMP"
mkdir -p "$TMP/Formula"
echo "$FORMULA" > "$TMP/Formula/${NAME}.rb"
cd "$TMP"
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add "Formula/${NAME}.rb"
git commit -m "${NAME} ${VERSION}"
git push
echo "==> pushed ${NAME} ${VERSION} to balintb/homebrew-tap" >&2
